name: generate_reflection
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  analyzer: ^5.1.0
  build: ^2.0.0
  universal_html_cpy:
    path: '..'

dev_dependencies:
  build_runner: ^2.4.4
  build_web_compilers: ^4.0.3
  lints: ^2.0.1